name: qr_code
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  cloud_firestore: ^4.5.3
  cupertino_icons: ^1.0.2
  firebase_core: ^2.10.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  http: ^0.13.5
  open_file: ^3.3.1
  path_provider: ^2.0.14
  pdf: ^3.6.0
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Nunito-Bold.ttf
    - assets/fonts/Nunito-Regular.ttf
